import 'package:flutter/material.dart';

class FraudAnalyticsScreen extends StatefulWidget {
  const FraudAnalyticsScreen({super.key});

  @override
  State<FraudAnalyticsScreen> createState() => _FraudAnalyticsScreenState();
}

// ============================================================================
// THEME COLORS
// ============================================================================
class ThemeColors {
  static const Color background = Color(0xFF060B18);
  static const Color surface = Color(0xFF0D1526);
  static const Color card = Color(0xFF111D35);
  static const Color borderGlow = Color(0xFF1E3A5F);
  static const Color accentBlue = Color(0xFF3B82F6);
  static const Color accentCyan = Color(0xFF06B6D4);
  static const Color safeGreen = Color(0xFF10B981);
  static const Color warningAmber = Color(0xFFF59E0B);
  static const Color dangerRed = Color(0xFFEF4444);
  static const Color purpleAccent = Color(0xFF8B5CF6);
  static const Color textPrimary = Color(0xFFE2E8F0);
  static const Color textMuted = Color(0xFF64748B);
}

// ============================================================================
// TEXT STYLES




































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































}  Size get screenSize => MediaQuery.of(this).size;extension on BuildContext {// ============================================================================// Utils// ============================================================================}  }    );      ),        ),          ),            ),              ),                ],                  ),                    ),                      ),                        ),                          fontSize: 10,                          color: gradientColors[0],                        style: AppTextStyles.caption.copyWith(                        card['badge'] as String,                      child: Text(                      ),                        ),                          color: gradientColors[0].withOpacity(0.3),                        border: Border.all(                        borderRadius: BorderRadius.circular(6),                        color: gradientColors[0].withOpacity(0.15),                      decoration: BoxDecoration(                      ),                        vertical: 4,                        horizontal: 8,                      padding: const EdgeInsets.symmetric(                    child: Container(                    right: 8,                    bottom: 8,                  Positioned(                  ),                    ],                      ),                        ),                          fontWeight: FontWeight.w600,                          color: gradientColors[0],                        style: AppTextStyles.bodyMedium.copyWith(                        card['value'] as String,                      Text(                      const SizedBox(height: 8),                      ),                        ),                          fontSize: 13,                        style: AppTextStyles.heading3.copyWith(                        textAlign: TextAlign.center,                        card['label'] as String,                      Text(                      const SizedBox(height: 12),                      ),                        ),                          ),                            style: const TextStyle(fontSize: 24),                            card['icon'] as String,                          child: Text(                        child: Center(                        ),                          ),                            color: gradientColors[0].withOpacity(0.4),                          border: Border.all(                          ),                            ],                              gradientColors[1].withOpacity(0.1),                              gradientColors[0].withOpacity(0.2),                            colors: [                            end: Alignment.bottomRight,                            begin: Alignment.topLeft,                          gradient: LinearGradient(                          shape: BoxShape.circle,                        decoration: BoxDecoration(                        height: 48,                        width: 48,                      Container(                    children: [                    crossAxisAlignment: CrossAxisAlignment.center,                    mainAxisAlignment: MainAxisAlignment.center,                  Column(                children: [              child: Stack(              padding: const EdgeInsets.all(16),            child: Padding(            ),              ],                  ),                    blurRadius: 0,                    color: Colors.transparent,                  BoxShadow(                else                  )                    offset: const Offset(0, 8),                    blurRadius: 20,                    color: gradientColors[0].withOpacity(0.3),                  BoxShadow(                if (_isHovered)              boxShadow: [              borderRadius: BorderRadius.circular(16),              ),                width: 1.5,                ),                  _isHovered ? 0.6 : 0.3,                color: gradientColors[0].withOpacity(              border: Border.all(              ),                ],                  gradientColors[1].withOpacity(0.05),                  gradientColors[0].withOpacity(0.15),                colors: [                end: Alignment.bottomRight,                begin: Alignment.topLeft,              gradient: LinearGradient(            decoration: BoxDecoration(          child: Container(          ),            CurvedAnimation(parent: _hoverController, curve: Curves.easeOut),          scale: Tween<double>(begin: 0.95, end: 1).animate(        child: ScaleTransition(        onTap: () {},      child: GestureDetector(      },        _hoverController.reverse();        setState(() => _isHovered = false);      onExit: (_) {      },        _hoverController.forward();        setState(() => _isHovered = true);      onEnter: (_) {    return MouseRegion(    final gradientColors = card['gradient'] as List<Color>;    final card = widget.card;  Widget build(BuildContext context) {  @override  }    super.dispose();    _hoverController.dispose();  void dispose() {  @override  }    );      vsync: this,      duration: const Duration(milliseconds: 300),    _hoverController = AnimationController(    super.initState();  void initState() {  @override  bool _isHovered = false;  late AnimationController _hoverController;    with TickerProviderStateMixin {class _FeatureCardState extends State<_FeatureCard>}  State<_FeatureCard> createState() => _FeatureCardState();  @override  });    required this.delay,    required this.card,  const _FeatureCard({  final Duration delay;  final Map<String, dynamic> card;class _FeatureCard extends StatefulWidget {}  }    );      ],        ),          ),            delay: Duration(milliseconds: 100 * index),            card: cards[index],          itemBuilder: (context, index) => _FeatureCard(          itemCount: cards.length,          ),            childAspectRatio: 1,            mainAxisSpacing: 12,            crossAxisSpacing: 12,            crossAxisCount: 2,          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(          physics: const NeverScrollableScrollPhysics(),          shrinkWrap: true,        GridView.builder(        const SizedBox(height: 16),        ),          style: AppTextStyles.heading2,          'Detection Features',        Text(      children: [      crossAxisAlignment: CrossAxisAlignment.start,    return Column(  Widget build(BuildContext context) {  @override  const _FeatureCardsGrid({required this.cards});  final List<Map<String, dynamic>> cards;class _FeatureCardsGrid extends StatelessWidget {// ============================================================================// FEATURE CARDS GRID// ============================================================================}  }    );      ],        ),          ),            ),              swapAnimationDuration: const Duration(milliseconds: 800),              ),                maxY: 40,                minY: 0,                maxX: (widget.data.length - 1).toDouble(),                minX: 0,                ],                  ),                    ),                      blurRadius: 8,                      color: ThemeColors.accentBlue.withOpacity(0.3),                    shadow: Shadow(                    ),                      ),                        ],                          ThemeColors.accentBlue.withOpacity(0.01),                          ThemeColors.accentBlue.withOpacity(0.3),                        colors: [                        end: Alignment.bottomCenter,                        begin: Alignment.topCenter,                      gradient: LinearGradient(                      show: true,                    belowBarData: BarAreaData(                    ),                      ),                        strokeColor: Colors.white,                        strokeWidth: 2,                        color: ThemeColors.accentBlue,                        radius: 6,                          FlDotCirclePainter(                      getDotPainter: (spot, percent, barData, index) =>                      show: true,                    dotData: FlDotData(                    barWidth: 3,                    color: ThemeColors.accentBlue,                    preventCurveOvershootingThreshold: 0,                    isCurved: true,                    ),                          FlSpot(index.toDouble(), widget.data[index]),                      (index) =>                      widget.data.length,                    spots: List.generate(                  LineChartBarData(                lineBarsData: [                ),                  show: false,                borderData: FlBorderData(                ),                  ),                    ),                      reservedSize: 35,                      },                        );                          style: AppTextStyles.caption,                          '${value.toInt()}',                        return Text(                      getTitlesWidget: (value, meta) {                      showTitles: true,                    sideTitles: SideTitles(                  leftTitles: AxisTitles(                  ),                    ),                      },                        );                          style: AppTextStyles.caption,                          widget.labels[value.toInt()],                        return Text(                        }                          return const SizedBox.shrink();                        if (value.toInt() >= widget.labels.length) {                      getTitlesWidget: (value, meta) {                      showTitles: true,                    sideTitles: SideTitles(                  bottomTitles: AxisTitles(                  ),                    sideTitles: SideTitles(showTitles: false),                  topTitles: AxisTitles(                  ),                    sideTitles: SideTitles(showTitles: false),                  rightTitles: AxisTitles(                  show: true,                titlesData: FlTitlesData(                ),                  },                    );                      dashArray: [5, 5],                      strokeWidth: 1,                      color: ThemeColors.borderGlow.withOpacity(0.2),                    return FlLine(                  getDrawingHorizontalLine: (value) {                  horizontalInterval: 10,                  drawVerticalLine: false,                  show: true,                gridData: FlGridData(              LineChartData(            child: LineChart(            height: 220,          child: SizedBox(          ),            borderRadius: BorderRadius.circular(16),            ),              color: ThemeColors.borderGlow.withOpacity(0.3),            border: Border.all(            ),              ],                ThemeColors.card.withOpacity(0.2),                ThemeColors.card.withOpacity(0.6),              colors: [              end: Alignment.bottomRight,              begin: Alignment.topLeft,            gradient: LinearGradient(          decoration: BoxDecoration(          padding: const EdgeInsets.all(16),        Container(        const SizedBox(height: 20),        ),          style: AppTextStyles.heading2,          'Fraud Trends - Weekly',        Text(      children: [      crossAxisAlignment: CrossAxisAlignment.start,    return Column(  Widget build(BuildContext context) {  @overrideclass _FraudTrendsChartState extends State<_FraudTrendsChart> {}  State<_FraudTrendsChart> createState() => _FraudTrendsChartState();  @override  });    required this.labels,    required this.data,  const _FraudTrendsChart({  final List<String> labels;  final List<double> data;class _FraudTrendsChart extends StatefulWidget {// ============================================================================// FRAUD TRENDS CHART// ============================================================================}  }    );      ],        ),          ),            color: color,          style: AppTextStyles.heading3.copyWith(          percentage,        Text(        ),          ),            ],              ),                style: AppTextStyles.caption,                '$value transactions',              Text(              const SizedBox(height: 2),              ),                style: AppTextStyles.bodySmall,                label,              Text(            children: [            crossAxisAlignment: CrossAxisAlignment.start,          child: Column(        Expanded(        const SizedBox(width: 8),        ),          ),            ],              ),                blurRadius: 6,                color: color.withOpacity(0.5),              BoxShadow(            boxShadow: [            color: color,            shape: BoxShape.circle,          decoration: BoxDecoration(          height: 12,          width: 12,        Container(      children: [    return Row(  Widget build(BuildContext context) {  @override  });    required this.value,    required this.percentage,    required this.label,    required this.color,  const _LegendItem({  final int value;  final String percentage;  final String label;  final Color color;class _LegendItem extends StatelessWidget {}      oldDelegate.animValue != animValue;  bool shouldRepaint(_DonutPainter oldDelegate) =>  @override  }    );      paint,      false,      highSweep,      startAngle,      Rect.fromCircle(center: center, radius: radius),    canvas.drawArc(    final highSweep = (high / 100) * 2 * math.pi * animValue;    paint.color = ThemeColors.dangerRed;    // High Risk (Red)    startAngle += mediumSweep;    );      paint..maskFilter = null,      false,      mediumSweep,      startAngle,      Rect.fromCircle(center: center, radius: radius),    canvas.drawArc(    final mediumSweep = (medium / 100) * 2 * math.pi * animValue;    paint.color = ThemeColors.warningAmber;    // Medium Risk (Amber)    startAngle += lowSweep;    );      paint..maskFilter = MaskFilter.blur(BlurStyle.outer, 8),      false,      lowSweep,      startAngle,      Rect.fromCircle(center: center, radius: radius),    canvas.drawArc(    final lowSweep = (low / 100) * 2 * math.pi * animValue;    paint.shader = null;    paint.color = ThemeColors.safeGreen;    // Low Risk (Green)    double startAngle = -math.pi / 2;      ..style = PaintingStyle.stroke;      ..strokeCap = StrokeCap.round      ..strokeWidth = strokeWidth    final paint = Paint()    const strokeWidth = 18.0;    final radius = size.width / 2 - 20;    final center = Offset(size.width / 2, size.height / 2);  void paint(Canvas canvas, Size size) {  @override  });    required this.high,    required this.medium,    required this.low,    required this.animValue,  _DonutPainter({  final double high;  final double medium;  final double low;  final double animValue;class _DonutPainter extends CustomPainter {}  }    );      ),        ),          ],            ),              style: AppTextStyles.bodySmall,              'Transactions',            Text(            const SizedBox(height: 4),            ),              ),                color: ThemeColors.accentBlue,              style: AppTextStyles.heading1.copyWith(              '${(low + medium + high).toInt()}',            Text(          children: [          mainAxisAlignment: MainAxisAlignment.center,        child: Column(      child: Center(      ),        high: high,        medium: medium,        low: low,        animValue: animation.value,      painter: _DonutPainter(    return CustomPaint(  Widget build(BuildContext context) {  @override  });    required this.high,    required this.medium,    required this.low,    required this.animation,  const _DonutChartPainter({  final double high;  final double medium;  final double low;  final Animation<double> animation;class _DonutChartPainter extends StatelessWidget {}  }    return (total * percentage / 100).toInt();  int _calculateCount(double percentage, int total) {  }    );      ],        ),          ],            ),              ),                ],                  ),                        widget.riskData['total']),                    value: _calculateCount(widget.riskData['high'],                    percentage: '${widget.riskData['high'].toStringAsFixed(0)}%',                    label: 'High Risk',                    color: ThemeColors.dangerRed,                  _LegendItem(                  const SizedBox(height: 12),                  ),                        widget.riskData['total']),                    value: _calculateCount(widget.riskData['medium'],                    percentage: '${widget.riskData['medium'].toStringAsFixed(0)}%',                    label: 'Medium Risk',                    color: ThemeColors.warningAmber,                  _LegendItem(                  const SizedBox(height: 12),                  ),                        widget.riskData['total']),                    value: _calculateCount(widget.riskData['low'],                    percentage: '${widget.riskData['low'].toStringAsFixed(0)}%',                    label: 'Low Risk',                    color: ThemeColors.safeGreen,                  _LegendItem(                children: [                crossAxisAlignment: CrossAxisAlignment.start,                mainAxisAlignment: MainAxisAlignment.center,              child: Column(              flex: 2,            Expanded(            const SizedBox(width: 20),            ),              ),                ),                  ),                    high: widget.riskData['high'],                    medium: widget.riskData['medium'],                    low: widget.riskData['low'],                    animation: _animController,                  child: _DonutChartPainter(                  height: 160,                child: SizedBox(                ),                  CurvedAnimation(parent: _animController, curve: Curves.easeOut),                scale: Tween<double>(begin: 0.8, end: 1).animate(              child: ScaleTransition(              flex: 2,            Expanded(          children: [          crossAxisAlignment: CrossAxisAlignment.start,        Row(        const SizedBox(height: 20),        ),          style: AppTextStyles.heading2,          'Risk Distribution',        Text(      children: [      crossAxisAlignment: CrossAxisAlignment.start,    return Column(  Widget build(BuildContext context) {  @override  }    super.dispose();    _animController.dispose();  void dispose() {  @override  }    )..forward();      vsync: this,      duration: const Duration(milliseconds: 1200),    _animController = AnimationController(    super.initState();  void initState() {  @override  late AnimationController _animController;    with TickerProviderStateMixin {class _RiskDistributionDonutState extends State<_RiskDistributionDonut>}      _RiskDistributionDonutState();  State<_RiskDistributionDonut> createState() =>  @override  const _RiskDistributionDonut({required this.riskData});  final Map<String, dynamic> riskData;class _RiskDistributionDonut extends StatefulWidget {// ============================================================================// RISK DISTRIBUTION DONUT// ============================================================================}  }    );      ),        ),          ],            ),              blurRadius: 8,              color: ThemeColors.safeGreen.withOpacity(0.6),            BoxShadow(          boxShadow: [          color: ThemeColors.safeGreen,          shape: BoxShape.circle,        decoration: BoxDecoration(        height: 8,        width: 8,      child: Container(      ),        CurvedAnimation(parent: controller, curve: Curves.easeInOut),      scale: Tween<double>(begin: 0.8, end: 1.2).animate(    return ScaleTransition(  Widget build(BuildContext context) {  @override  const _PulsingDot({required this.controller});  final AnimationController controller;class _PulsingDot extends StatelessWidget {// ============================================================================// PULSING DOT// ============================================================================}  }    );      ),        ),          ],            ),              ),                ),                  ),                    color: color,                    borderRadius: BorderRadius.circular(2),                  decoration: BoxDecoration(                child: Container(                alignment: Alignment.centerLeft,                widthFactor: 0.7,              child: FractionallySizedBox(              ),                color: color.withOpacity(0.3),                borderRadius: BorderRadius.circular(2),              decoration: BoxDecoration(              height: 3,            Container(            const SizedBox(height: 8),            ),              },                );                  ),                    color: color,                  style: AppTextStyles.heading3.copyWith(                  value.toString(),                return Text(                }                  );                    ),                      color: color,                    style: AppTextStyles.heading3.copyWith(                    animatedValue.toString(),                  return Text(                      (value * _counterController.value).toInt();                  final animatedValue =                if (value is int) {                final value = data['value'];              builder: (context, child) {              animation: _counterController,            AnimatedBuilder(            const SizedBox(height: 8),            ),              style: AppTextStyles.bodySmall,              data['label'] as String,            Text(            const SizedBox(height: 12),            ),              ],                ),                  ),                    ),                      fontWeight: FontWeight.w600,                      color: ThemeColors.warningAmber,                    style: AppTextStyles.caption.copyWith(                    data['change'] as String,                  child: Text(                  ),                    ),                      color: ThemeColors.warningAmber.withOpacity(0.3),                    border: Border.all(                    borderRadius: BorderRadius.circular(6),                    color: ThemeColors.warningAmber.withOpacity(0.15),                  decoration: BoxDecoration(                  ),                    vertical: 4,                    horizontal: 8,                  padding: const EdgeInsets.symmetric(                Container(                ),                  style: const TextStyle(fontSize: 20),                  data['icon'] as String,                Text(              children: [              mainAxisAlignment: MainAxisAlignment.spaceBetween,            Row(          children: [          crossAxisAlignment: CrossAxisAlignment.start,        child: Column(        padding: const EdgeInsets.all(16),      child: Padding(      ),        ],          ),            offset: const Offset(0, 8),            blurRadius: 20,            color: color.withOpacity(0.15),          BoxShadow(        boxShadow: [        borderRadius: BorderRadius.circular(16),        ),          width: 1.2,          color: color.withOpacity(0.3),        border: Border.all(        ),          ],            ThemeColors.card.withOpacity(0.2),            ThemeColors.card.withOpacity(0.6),          colors: [          end: Alignment.bottomRight,          begin: Alignment.topLeft,        gradient: LinearGradient(      decoration: BoxDecoration(    return Container(    final color = data['color'] as Color;    final data = widget.data;  Widget build(BuildContext context) {  @override  }    super.dispose();    _counterController.dispose();  void dispose() {  @override  }    });      if (mounted) _counterController.forward();    Future.delayed(widget.delay, () {    );      vsync: this,      duration: const Duration(milliseconds: 1600),    _counterController = AnimationController(    super.initState();  void initState() {  @override  late AnimationController _counterController;class _StatCardState extends State<_StatCard> with TickerProviderStateMixin {}  State<_StatCard> createState() => _StatCardState();  @override  });    required this.delay,    required this.data,  const _StatCard({  final Duration delay;  final Map<String, dynamic> data;class _StatCard extends StatefulWidget {}  }    return amount.toString();    }      return '${(amount / 1000).toStringAsFixed(0)}K';    } else if (amount >= 1000) {      return '${(amount / 1000000).toStringAsFixed(1)}M';    if (amount >= 1000000) {  String _formatAmount(int amount) {  }    );      ),        ),          ),            delay: Duration(milliseconds: 100 * index),            data: statItems[index],          child: _StatCard(        (index) => Expanded(        statItems.length,      children: List.generate(    return Row(    ];      },        'change': '+${stats['changePercents'][2]}%',        'color': ThemeColors.accentBlue,        'icon': '📊',        'value': stats['txnsScanned'],        'label': 'TXNs Scanned',      {      },        'change': '+${stats['changePercents'][1]}%',        'color': ThemeColors.safeGreen,        'icon': '💰',        'value': _formatAmount(stats['protectedAmount']),        'label': 'Protected (₹)',      {      },        'change': '+${stats['changePercents'][0]}%',        'color': ThemeColors.dangerRed,        'icon': '🛡️',        'value': stats['fraudBlocked'],        'label': 'Fraud Blocked',      {    final statItems = [  Widget build(BuildContext context) {  @override  const _StatsRow({required this.stats});  final Map<String, dynamic> stats;class _StatsRow extends StatelessWidget {// ============================================================================// STATS ROW// ============================================================================}  }    );      ),        }),          );            ),              ),                ),                  ),                    ),                      ),                        ),                          fontSize: 14,                              : ThemeColors.textMuted,                              ? Colors.white                          color: isSelected                        style: AppTextStyles.heading3.copyWith(                        options[index],                      child: Text(                    child: Center(                    padding: const EdgeInsets.symmetric(vertical: 12),                  child: Padding(                  borderRadius: BorderRadius.circular(16),                  onTap: () => widget.onChanged(options[index]),                child: InkWell(                color: Colors.transparent,              child: Material(              ),                borderRadius: BorderRadius.circular(16),                    : null,                      )                        ],                          ThemeColors.accentCyan.withOpacity(0.8),                          ThemeColors.accentBlue,                        colors: [                        end: Alignment.bottomRight,                        begin: Alignment.topLeft,                    ? LinearGradient(                gradient: isSelected              decoration: BoxDecoration(              curve: Curves.easeInOutCubic,              duration: const Duration(milliseconds: 300),            child: AnimatedContainer(          return Expanded(          final isSelected = index == selectedIndex;        children: List.generate(options.length, (index) {      child: Row(      ),        ),          color: ThemeColors.borderGlow.withOpacity(0.3),        border: Border.all(        borderRadius: BorderRadius.circular(20),        color: ThemeColors.card.withOpacity(0.5),      decoration: BoxDecoration(      padding: const EdgeInsets.all(6),    return Container(    final selectedIndex = options.indexOf(widget.selected);    final options = ['Week', 'Month', 'Year'];  Widget build(BuildContext context) {  @override  }    super.dispose();    _slideController.dispose();  void dispose() {  @override  }    }      _slideController.forward(from: 0);    if (oldWidget.selected != widget.selected) {    super.didUpdateWidget(oldWidget);  void didUpdateWidget(_TimeFilterTabs oldWidget) {  @override  }    );      vsync: this,      duration: const Duration(milliseconds: 300),    _slideController = AnimationController(    super.initState();  void initState() {  @override  late AnimationController _slideController;    with SingleTickerProviderStateMixin {class _TimeFilterTabsState extends State<_TimeFilterTabs>}  State<_TimeFilterTabs> createState() => _TimeFilterTabsState();  @override  });    required this.onChanged,    required this.selected,  const _TimeFilterTabs({  final ValueChanged<String> onChanged;  final String selected;class _TimeFilterTabs extends StatefulWidget {// ============================================================================// TIME FILTER TABS// ============================================================================}  }    return '${now.day} ${months[now.month - 1]}';    ];      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',    final months = [    final now = DateTime.now();  String _getFormattedDate() {  }    );      ),        child: child,        ),          ),            ),              curve: Curves.easeOut,              (delay.inMilliseconds + 400) / 1200,              delay.inMilliseconds / 1200,            curve: Interval(            parent: _fadeController,          CurvedAnimation(        ).animate(          end: Offset.zero,          begin: const Offset(0, 0.2),        position: Tween<Offset>(      child: SlideTransition(      ),        ),          ),            curve: Curves.easeOut,            (delay.inMilliseconds + 400) / 1200,            delay.inMilliseconds / 1200,          curve: Interval(          parent: _fadeController,        CurvedAnimation(      opacity: Tween<double>(begin: 0, end: 1).animate(    return FadeTransition(  }) {    required Widget child,    required Duration delay,  Widget _buildAnimatedSection({  }    );      ),        ),          ),            ),              ),                ],                  SizedBox(width: 40),                  ),                    ),                      ],                        ),                          ],                            ),                              style: AppTextStyles.caption,                              'System Active • ${_getFormattedDate()}',                            Text(                            const SizedBox(width: 8),                            _PulsingDot(controller: _pulseController),                          children: [                          mainAxisAlignment: MainAxisAlignment.center,                        Row(                        const SizedBox(height: 4),                        ),                          ),                            ),                              color: Colors.white,                            style: AppTextStyles.heading2.copyWith(                            'Fraud Analytics',                          child: Text(                          },                            ).createShader(bounds);                              ],                                ThemeColors.accentCyan,                                ThemeColors.accentBlue,                              colors: [                              end: Alignment.bottomRight,                              begin: Alignment.topLeft,                            return LinearGradient(                          shaderCallback: (bounds) {                        ShaderMask(                      children: [                      mainAxisSize: MainAxisSize.min,                      crossAxisAlignment: CrossAxisAlignment.center,                    child: Column(                  Expanded(                  ),                    ),                      ),                        ),                          ),                            size: 18,                            color: ThemeColors.accentBlue,                            Icons.arrow_back_ios_new,                          child: const Icon(                          ),                            ),                              color: ThemeColors.borderGlow.withOpacity(0.3),                            border: Border.all(                            borderRadius: BorderRadius.circular(12),                          decoration: BoxDecoration(                        child: Container(                        borderRadius: BorderRadius.circular(12),                        onTap: () => Navigator.pop(context),                      child: InkWell(                      color: Colors.transparent,                    child: Material(                    height: 40,                    width: 40,                  SizedBox(                children: [                mainAxisAlignment: MainAxisAlignment.spaceBetween,              child: Row(              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),            child: Padding(            bottom: false,          child: SafeArea(          filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),        child: BackdropFilter(      child: ClipRect(      ),        ),          ),            color: ThemeColors.borderGlow.withOpacity(0.2),          bottom: BorderSide(        border: Border(        color: ThemeColors.surface.withOpacity(0.4),      decoration: BoxDecoration(    return Container(  Widget _buildBlurredHeader() {  // ========================================================================  // Helper Widgets  // ========================================================================  }    );      ),        ),          ],            ),              ),                ],                  const SizedBox(height: 32),                  ),                    child: _FeatureCardsGrid(cards: featureCards),                    delay: const Duration(milliseconds: 600),                  _buildAnimatedSection(                  const SizedBox(height: 32),                  ),                    ),                      labels: trendLabels,                      data: trendData,                    child: _FraudTrendsChart(                    delay: const Duration(milliseconds: 450),                  _buildAnimatedSection(                  const SizedBox(height: 32),                  ),                    child: _RiskDistributionDonut(riskData: riskData),                    delay: const Duration(milliseconds: 300),                  _buildAnimatedSection(                  const SizedBox(height: 32),                  ),                    child: _StatsRow(stats: stats),                    delay: const Duration(milliseconds: 150),                  _buildAnimatedSection(                  const SizedBox(height: 28),                  ),                    ),                      },                        setState(() => _selectedTimeRange = value);                      onChanged: (value) {                      selected: _selectedTimeRange,                    child: _TimeFilterTabs(                    delay: Duration.zero,                  _buildAnimatedSection(                  const SizedBox(height: 24),                children: [              child: Column(              padding: const EdgeInsets.symmetric(horizontal: 16),            Padding(            // Main content with staggered animations                        _buildBlurredHeader(),            // Header with blur effect          children: [        child: Column(        physics: const BouncingScrollPhysics(),      body: SingleChildScrollView(      backgroundColor: ThemeColors.background,    return Scaffold(  Widget build(BuildContext context) {  @override  }    super.dispose();    _contentController.dispose();    _fadeController.dispose();    _pulseController.dispose();  void dispose() {  @override  }    )..forward();      vsync: this,      duration: const Duration(milliseconds: 1200),    _contentController = AnimationController(    )..forward();      vsync: this,      duration: const Duration(milliseconds: 600),    _fadeController = AnimationController(    )..repeat();      vsync: this,      duration: const Duration(milliseconds: 1500),    _pulseController = AnimationController(    super.initState();  void initState() {  @override  ];    },      'gradient': [Color(0xFF8B5CF6), Color(0xFFA78BFA)],      'badge': 'Risk',      'value': 'High',      'label': 'Velocity',      'icon': '⚡',    {    },      'gradient': [Color(0xFF3B82F6), Color(0xFF60A5FA)],      'badge': 'new',      'value': '3',      'label': 'New Device',      'icon': '🔧',    {    },      'gradient': [Color(0xFFF59E0B), Color(0xFFFCBF49)],      'badge': 'avg',      'value': '+340%',      'label': 'Amount Spike',      'icon': '📈',    {    },      'gradient': [Color(0xFFEF4444), Color(0xFFFCA5A5)],      'badge': 'flagged',      'value': '12',      'label': 'Suspicious VPA',      'icon': '⚠️',    {  final featureCards = [  final trendLabels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];  final trendData = [12.0, 8.0, 19.0, 6.0, 23.0, 14.0, 31.0];  };    'total': 1284,    'high': 10.0,    'medium': 22.0,    'low': 68.0,  final riskData = {  };    'changePercents': [12, 8, 15],    'txnsScanned': 1284,    'protectedAmount': 2840000,    'fraudBlocked': 47,  final stats = {  // Mock data  String _selectedTimeRange = 'Week';  late AnimationController _contentController;  late AnimationController _fadeController;  late AnimationController _pulseController;    with TickerProviderStateMixin {class _FraudAnalyticsScreenState extends State<FraudAnalyticsScreen>// ============================================================================// MAIN SCREEN STATE// ============================================================================}  );    letterSpacing: 0.5,    color: ThemeColors.textMuted,    fontWeight: FontWeight.w400,    fontSize: 11,  static TextStyle caption = TextStyle(fontFamily: 'Manrope',   );    color: ThemeColors.textMuted,    fontWeight: FontWeight.w400,    fontSize: 12,  static TextStyle bodySmall = TextStyle(fontFamily: 'Manrope',   );    color: ThemeColors.textPrimary,    fontWeight: FontWeight.w400,    fontSize: 14,  static TextStyle bodyMedium = TextStyle(fontFamily: 'Manrope',   );    color: ThemeColors.textPrimary,    fontWeight: FontWeight.w500,    fontSize: 16,  static TextStyle bodyLarge = TextStyle(fontFamily: 'Manrope',   );    color: ThemeColors.textPrimary,    fontWeight: FontWeight.w600,    fontSize: 16,  static TextStyle heading3 = TextStyle(fontFamily: 'Manrope',   );    letterSpacing: -0.3,    color: ThemeColors.textPrimary,    fontWeight: FontWeight.w700,    fontSize: 20,  static TextStyle heading2 = TextStyle(fontFamily: 'Manrope',   );    letterSpacing: -0.5,    color: ThemeColors.textPrimary,    fontWeight: FontWeight.w700,    fontSize: 28,  static TextStyle heading1 = TextStyle(fontFamily: 'Manrope', class AppTextStyles {// ============================================================================
